
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class Events
{

    public int eventId { get; set; }

    public string eventName { get; set; }

    public string eventDate { get; set; }

    public int eventPrice { get; set; }

    public string eventStatus { get; set; }

}

}
