
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentForMisc
{

    public int paymentId { get; set; }

    public string userName { get; set; }

    public string userIdNumber { get; set; }

    public string yearLvl { get; set; }

    public string miscName { get; set; }

    public Nullable<System.DateTime> paymentdate { get; set; }

    public Nullable<int> miscPrice { get; set; }

}

}
