
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class vw_total_applicants_4thyr
{

    public int eventId { get; set; }

    public Nullable<int> C4th_Year_Applicants { get; set; }

    public string Event { get; set; }

}

}
